
server {
    listen 8080 default_server;
    server_name ~^.*$;
    root /usr/share/nginx/html;
    index index.html;
    location /api {
        proxy_pass http://localhost:3000/api;
    }
    location /uploads {
        proxy_pass http://localhost:3000/uploads;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
