services:

  IPEXCO_FRONTEND:
    container_name: ipexco-frontend
    image: eifler/ipexco-eval-frontend:latest
    ports:
      - "4200:80"

  IPEXCO_BACKEND:
    container_name: ipexco-backend
    image: eifler/ipexco-eval-backend:latest
    volumes:
      - <absolute bath to local folder>:/usr/src/app/dist/out-tsc/data
    ports:
      - "3000:3000"
    env_file:
        - backend.env

  DATABASE:
    container_name: mongo
    image: mongo
    volumes:
      - <absolute bath to local folder>/:/data/db
    ports:
      - "27017:27017"
