import { StylesheetJson } from "cytoscape";

export const PLANPILOT_GRAPH_STYLES: StylesheetJson = [
  {
    selector: "node",
    style: {
      "background-color": "#ffffff",
      "border-color": "#aeb8c2",
      "border-width": 1.5,
      color: "#151a1f",
      "font-family": "Roboto, sans-serif",
      "font-size": 13,
      height: 80,
      label: "data(label)",
      "overlay-opacity": 0,
      shape: "round-rectangle",
      "text-halign": "center",
      "text-max-width": "184px",
      "text-valign": "center",
      "text-wrap": "wrap",
      width: 216,
    },
  },
  {
    selector: "node.facet.root",
    style: {
      "background-color": "#0f766e",
      "border-color": "#115e59",
      "border-width": 3,
      color: "#ffffff",
      shape: "ellipse",
      height: 112,
      width: 184,
    },
  },
  {
    selector: "node.facet.goal",
    style: {
      "background-color": "#fef3c7",
      "border-color": "#b45309",
      "border-style": "solid",
      "border-width": 3,
      color: "#78350f",
      opacity: 1,
      shape: "diamond",
      "text-max-width": "108px",
      height: 132,
      width: 184,
    },
  },
  {
    selector: "node.time",
    style: {
      "background-color": "#f2f6f7",
      "border-color": "#6b7d86",
      "border-style": "solid",
      "font-size": 12,
      height: 46,
      shape: "round-rectangle",
      width: 128,
    },
  },
  {
    selector: "node.alternative",
    style: {
      "background-color": "#fff7ed",
      "border-color": "#c2410c",
      "border-style": "dashed",
    },
  },
  {
    selector: "node.query",
    style: {
      "background-color": "#f1f5f9",
      "border-color": "#64748b",
      shape: "round-rectangle",
    },
  },
  {
    selector: "node.implied",
    style: {
      "background-color": "#f8fafc",
      "border-color": "#64748b",
      "border-style": "dotted",
    },
  },
  {
    selector: "node.empty",
    style: {
      "background-color": "#f1f5f9",
      "border-color": "#64748b",
      "border-style": "dotted",
      color: "#475569",
    },
  },
  {
    selector: "node.unavailable",
    style: {
      "background-color": "#f2f4f6",
      "border-color": "#9aa6af",
      "border-style": "dotted",
      color: "#66727c",
      opacity: 0.58,
    },
  },
  {
    selector: "node.facet",
    style: {
      height: 80,
      width: 216,
    },
  },
  {
    selector: "node.required",
    style: {
      "background-color": "#dbeafe",
      "border-color": "#2563eb",
      "border-width": 4,
    },
  },
  {
    selector: "node.forbidden",
    style: {
      "background-color": "#ffe0db",
      "border-color": "#b91c1c",
      "border-style": "double",
      "border-width": 4,
    },
  },
  {
    selector: "node.displayed-plan",
    style: {
      "background-color": "#dcfce7",
      "border-color": "#15803d",
      "border-style": "solid",
      "border-width": 3,
      opacity: 1,
    },
  },
  {
    selector: "node.displayed-plan.user-constraint",
    style: {
      "background-color": "#dcfce7",
      "border-color": "#2563eb",
      "border-width": 5,
    },
  },
  {
    selector: "node.displayed-plan.user-constraint.negative",
    style: {
      "background-color": "#ffe0db",
      "border-color": "#b91c1c",
      "border-style": "double",
      "border-width": 4,
    },
  },
  {
    selector: "node.level-anchor",
    style: {
      width: 1,
      height: 1,
      opacity: 0,
      label: "",
      events: "no",
    },
  },
  {
    selector: "node.selected",
    style: {
      "overlay-color": "#005f73",
      "overlay-opacity": 0.16,
      "overlay-padding": 8,
    },
  },
  {
    selector: "edge",
    style: {
      "curve-style": "taxi",
      "taxi-direction": "downward",
      "taxi-turn": 42,
      "line-color": "#64748b",
      "arrow-scale": 1.25,
      "source-arrow-shape": "none",
      "target-arrow-color": "#64748b",
      "target-arrow-shape": "triangle",
      "target-arrow-fill": "filled",
      color: "#34424e",
      "font-size": 10,
      "text-background-color": "#f4f7f9",
      "text-background-opacity": 0.85,
      "text-background-padding": "2px",
      width: 2.6,
    },
  },
  {
    selector: "edge.plan-edge",
    style: {
      label: "data(label)",
      "arrow-scale": 2,
      "line-color": "#087f5b",
      "target-arrow-color": "#087f5b",
      "target-arrow-shape": "triangle",
      opacity: 1,
      "text-rotation": "autorotate",
      "text-background-color": "#ecfdf5",
      "text-background-opacity": 1,
      "text-background-padding": "3px",
      width: 8,
      "z-index": 20,
    },
  },
  {
    selector: "edge.level-edge",
    style: {
      "curve-style": "straight",
      "line-color": "#cbd5e1",
      "line-style": "dashed",
      "target-arrow-shape": "none",
      label: "data(label)",
      color: "#64748b",
      "font-size": 12,
      "text-background-color": "#f8fafc",
      "text-background-opacity": 0.95,
      "text-background-padding": "3px",
      width: 1.5,
      events: "no",
      "z-index": 0,
    },
  },
];
