services:

  DEMO_FRONTEND:
      container_name: beluga-demo-frontend
      image: eifler/beluga-demo-frontend:latest
      ports:
        - "4080:80"

  DEMO_BACKEND:
    container_name: beluga-demo-backend
    image: eifler/beluga-demo-backend:latest
    volumes:
      - ./backend_data:/usr/src/app/dist/out-tsc/data
    ports:
      - "3000:3000"
    env_file:
        - backend.env

  PLANNER_BELUGA:
    container_name: test_planner_beluga
    image: eifler/simple-beluga-planner:latest
    ports:
      - "3336:3336"
    env_file:
        - planner.env

  DATABASE:
    container_name: test_mongo_beluga
    image: mongo
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"
